empresa_xyz/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('', include('website.urls', namespace='website')),

    path('admin/', admin.site.urls),
]

website/urls.py
from website.views import IndexTemplateView, EmpresaListView, EmpresaUpdateView, EmpresaCreateView, \
    EmpresaDeleteView, ServicoListView, ServicoUpdateView, ServicoCreateView, ServicoDeleteView, \
    VendedorListView, VendedorUpdateView, VendedorCreateView, VendedorDeleteView, VendaListView, \
    VendaUpdateView, VendaCreateView, VendaDeleteView

from django.urls import path

app_name = 'website'

urlpatterns = [
    # GET /
    path('', IndexTemplateView.as_view(), name="index"),

    # GET /empresa/cadastrar
    path('empresa/cadastrar', EmpresaCreateView.as_view(), name="cadastra_empresa"),

    # GET /empresas
    path('empresas/', EmpresaListView.as_view(), name="lista_empresas"),

    # GET/POST /empresa/{pk}
    path('empresa/<pk>', EmpresaUpdateView.as_view(), name="atualiza_empresa"),

    # GET/POST /empresas/excluir/{pk}
    path('empresa/excluir/<pk>', EmpresaDeleteView.as_view(), name="deleta_empresa"),

    ##################################################################################

    # GET /servico/cadastrar
    path('servico/cadastrar', ServicoCreateView.as_view(), name="cadastra_servico"),

    # GET /servicos
    path('servicos/', ServicoListView.as_view(), name="lista_servicos"),

    # GET/POST /servico/{pk}
    path('servico/<pk>', ServicoUpdateView.as_view(), name="atualiza_servico"),

    # GET/POST /servicos/excluir/{pk}
    path('servico/excluir/<pk>', ServicoDeleteView.as_view(), name="deleta_servico"),

    ##################################################################################

    # GET /vendedor/cadastrar
    path('vendedor/cadastrar', VendedorCreateView.as_view(), name="cadastra_vendedor"),

    # GET /vendedores
    path('vendedores/', VendedorListView.as_view(), name="lista_vendedores"),

    # GET/POST /vendedor/{pk}
    path('vendedor/<pk>', VendedorUpdateView.as_view(), name="atualiza_vendedor"),

    # GET/POST /vendedores/excluir/{pk}
    path('vendedor/excluir/<pk>', VendedorDeleteView.as_view(), name="deleta_vendedor"),

    # Testando chamada de Vendedores por empresa
    #path('vendedores/', VendedorEmpresa.as_view(), name="vendedor_empresa")

    ##################################################################################

    # GET /venda/cadastrar
    path('venda/cadastrar', VendaCreateView.as_view(), name="cadastra_venda"),

    # GET /vendas
    path('vendas/', VendaListView.as_view(), name="lista_vendas"),

    # GET/POST /venda/{pk}
    path('venda/<pk>', VendaUpdateView.as_view(), name="atualiza_venda"),

    # GET/POST /vendas/excluir/{pk}
    path('venda/excluir/<pk>', VendaDeleteView.as_view(), name="deleta_venda"),

]

website/forms.py
from empresa_xyz.models import Empresa, Servico, Vendedor, Venda
from django import forms


# FORMULÁRIO DE CADASTRO DE EMPRESAS

class InsereEmpresaForm(forms.ModelForm):

    class Meta:
        model = Empresa

        fields = [
            'nome',
            'cnpj',
        ]

# FORMULÁRIO DE CADASTRO DE EMPRESAS

class InsereServicoForm(forms.ModelForm):

    class Meta:
        model = Servico

        fields = [
            'nome_servico',
            'comissao_servico',
            'empresa_prestadora',
            'preco',
        ]

# FORMULÁRIO DE CADASTRO DE VENDEDORES

class InsereVendedorForm(forms.ModelForm):

    class Meta:
        model = Vendedor

        fields = [
            'nome_vendedor',
            'comissao_vendedor',
            'empresa_vendedor',
        ]

# FORMULÁRIO DE VENDAS

class InsereVendaForm(forms.ModelForm):

    class Meta:
        model = Venda

        fields = [
            'id_empresa',
            'id_vendedor',
            'id_servico',
        ]

website/views.py
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, UpdateView, CreateView, DeleteView
from empresa_xyz.models import Empresa, Servico, Vendedor, Venda
from website.forms import InsereEmpresaForm, InsereServicoForm, InsereVendedorForm, InsereVendaForm
from django.shortcuts import render


# PÁGINA PRINCIPAL
class IndexTemplateView(TemplateView):
    template_name = "website/index.html"


# LISTA DE EMPRESAS
class EmpresaListView(ListView):
    template_name = "website/lista.html"
    model = Empresa
    context_object_name = "empresas"


# CADASTRAMENTO DE EMPRESAS
class EmpresaCreateView(CreateView):
    template_name = "website/cria.html"
    model = Empresa
    form_class = InsereEmpresaForm
    success_url = reverse_lazy("website:lista_empresas")


# ATUALIZAÇÃO DE EMPRESAS
class EmpresaUpdateView(UpdateView):
    template_name = "website/atualiza.html"
    model = Empresa
    fields = '__all__'
    context_object_name = 'empresa'
    success_url = reverse_lazy("website:lista_empresas")


# EXCLUSÃO DE EMPRESAS
class EmpresaDeleteView(DeleteView):
    template_name = "website/exclui.html"
    model = Empresa
    context_object_name = 'empresa'
    success_url = reverse_lazy("website:lista_empresas")

########################################################

# LISTA DE SERVICOS
class ServicoListView(ListView):
    template_name = "website/lista_servico.html"
    model = Servico
    context_object_name = "servicos"


# CADASTRAMENTO DE SERVICOS
class ServicoCreateView(CreateView):
    template_name = "website/cria_servico.html"
    model = Servico
    form_class = InsereServicoForm
    success_url = reverse_lazy("website:lista_servicos")


# ATUALIZAÇÃO DE SERVICOS
class ServicoUpdateView(UpdateView):
    template_name = "website/atualiza_servico.html"
    model = Servico
    fields = '__all__'
    context_object_name = 'servico'
    success_url = reverse_lazy("website:lista_servicos")


# EXCLUSÃO DE SERVICOS
class ServicoDeleteView(DeleteView):
    template_name = "website/exclui_servico.html"
    model = Servico
    context_object_name = 'servico'
    success_url = reverse_lazy("website:lista_servicos")

###########################################################

# LISTA DE VENDEDORES
class VendedorListView(ListView):
    template_name = "website/lista_vendedor.html"
    model = Vendedor
    context_object_name = "vendedores"


# CADASTRAMENTO DE VENDEDORES
class VendedorCreateView(CreateView):
    template_name = "website/cria_vendedor.html"
    model = Vendedor
    form_class = InsereVendedorForm
    success_url = reverse_lazy("website:lista_vendedores")


# ATUALIZAÇÃO DE VENDEDORES
class VendedorUpdateView(UpdateView):
    template_name = "website/atualiza_vendedor.html"
    model = Vendedor
    fields = '__all__'
    context_object_name = 'vendedor'
    success_url = reverse_lazy("website:lista_vendedores")


# EXCLUSÃO DE VENDEDORES
class VendedorDeleteView(DeleteView):
    template_name = "website/exclui_vendedor.html"
    model = Vendedor
    context_object_name = 'vendedor'
    success_url = reverse_lazy("website:lista_vendedores")


###########################################################

# VENDAS REALIZADAS
class VendaListView(ListView):
    template_name = "website/lista_venda.html"
    model = Venda
    context_object_name = "vendas"

# CADASTRAMENTO DE VENDAS
class VendaCreateView(CreateView):
    template_name = "website/cria_venda.html"
    model = Venda
    form_class = InsereVendaForm
    success_url = reverse_lazy("website:lista_vendas")

# ATUALIZAÇÃO DE VENDAS
class VendaUpdateView(UpdateView):
    template_name = "website/atualiza_venda.html"
    model = Venda
    fields = '__all__'
    context_object_name = 'venda'
    success_url = reverse_lazy("website:lista_vendas")

# EXCLUSÃO DE VENDAS
class VendaDeleteView(DeleteView):
    template_name = "website/exclui_venda.html"
    model = Venda
    context_object_name = 'venda'
    success_url = reverse_lazy("website:lista_vendas")

###########################################################

'''def VendedorEmpresa(request):
    vendedores = Vendedor.objetos.all()

    contexto = {
        'vendedores': vendedores
    }

    return render(
        request,
        "templates/vendedor_empresa.html",
        contexto
    )'''

'''class VendedorEmpresa(UpdateView):
    template_name = "website/vendedor_empresa.html"
    model = Vendedor
    fields = '__all__'
    context_object_name = "vendedores"

    def get_object(self, queryset=None, nome_empresa):
        vendedor = None
        id = self.kwargs.get(self.pk_url_kwarg)

        if id is not None:
            vendedor = Vendedor.objetos.filter(id=id).filter(empresa_vendedor=nome_empresa).all()

        return vendedor'''

website/templates/website/atualiza.html
{% extends "website/_layouts/base.html" %}

{% load widget_tweaks %}

{% block title %}Atualização de Empresa{% endblock %}

{% block conteudo %}
<div class="container mt-5">
  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Atualizar Dados da Empresa</h5>
          <form method="post">
            <!-- Não se esqueça dessa tag -->
            {% csrf_token %}

            <!-- Nome -->
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">Nome</span>
              </div>
              {% render_field form.nome class+="form-control" %}
            </div>

            <!-- CNPJ -->
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">CNPJ</span>
              </div>
              {% render_field form.cnpj class+="form-control" %}
            </div>

            <hr />
            <div class="text-right">
              <a href="{% url 'website:lista_empresas' %}" class="btn btn-outline-primary">Voltar</a>
              <button class="btn btn-primary">Enviar</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

website/templates/website/atualiza_servico.html
{% extends "website/_layouts/base.html" %}

{% load widget_tweaks %}

{% block title %}Atualização de Serviço{% endblock %}

{% block conteudo %}
<div class="container mt-5">
  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Atualizar Serviços</h5>
          <form method="post">
            <!-- Não se esqueça dessa tag -->
            {% csrf_token %}

            <!-- Nome -->
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">Nome</span>
              </div>
              {% render_field form.nome_servico class+="form-control" %}
            </div>
            <!-- Preço -->
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">Preço</span>
              </div>
              {% render_field form.preco class+="form-control" %}
            </div>

            <!-- Comissão -->
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">Comissão</span>
              </div>
              {% render_field form.comissao_servico class+="form-control" %}
            </div>

            <!-- Prestadora -->
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">Prestadora</span>
              </div>
              {% render_field form.empresa_prestadora class+="form-control" %}
            </div>

            <hr />
            <div class="text-right">
              <a href="{% url 'website:lista_servicos' %}" class="btn btn-outline-primary">Voltar</a>
              <button class="btn btn-primary">Enviar</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

website/templates/website/atualiza_venda.html
{% extends "website/_layouts/base.html" %}

{% load widget_tweaks %}

{% block title %}Atualização de Vendas{% endblock %}

{% block conteudo %}
<div class="container mt-5">
  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Atualizar Vendas</h5>
          <form method="post">
            <!-- Não se esqueça dessa tag -->
            {% csrf_token %}

            <!-- Servico -->
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">Serviço</span>
              </div>
              {% render_field form.id_servico class+="form-control" %}
            </div>

            <!-- Empresa -->
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">Empresa</span>
              </div>
              {% render_field form.id_empresa class+="form-control" %}
            </div>

            <!-- Vendedor -->
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">Vendedor</span>
              </div>
              {% render_field form.id_vendedor class+="form-control" %}
            </div>

            <hr />
            <div class="text-right">
              <a href="{% url 'website:lista_vendas' %}" class="btn btn-outline-primary">Voltar</a>
              <button class="btn btn-primary">Enviar</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

website/templates/website/atualiza_vendedor.html
{% extends "website/_layouts/base.html" %}

{% load widget_tweaks %}

{% block title %}Atualização de Vendedores{% endblock %}

{% block conteudo %}
<div class="container mt-5">
  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Atualizar Vendedores</h5>
          <form method="post">
            <!-- Não se esqueça dessa tag -->
            {% csrf_token %}

            <!-- Nome -->
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">Nome</span>
              </div>
              {% render_field form.nome_vendedor class+="form-control" %}
            </div>

            <!-- Comissão -->
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">Comissão</span>
              </div>
              {% render_field form.comissao_vendedor class+="form-control" %}
            </div>

            <!-- Empresa em que trabalha -->
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">Empresa</span>
              </div>
              {% render_field form.empresa_vendedor class+="form-control" %}
            </div>

            <hr />
            <div class="text-right">
              <a href="{% url 'website:lista_vendedores' %}" class="btn btn-outline-primary">Voltar</a>
              <button class="btn btn-primary">Enviar</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

website/templates/website/cria.html
{% extends "website/_layouts/base.html" %}

{% load widget_tweaks %}

{% block title %}Cadastro de Empresas{% endblock %}

{% block conteudo %}
<div class="container mt-5">
  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Cadastro de Empresa</h5>
          <p class="card-text">
            Complete o formulário abaixo para cadastrar
            uma nova <code>Empresa</code>.
          </p>
          <form method="post">
            <!-- Não se esqueça dessa tag -->
            {% csrf_token %}

            <!-- Nome da Empresa -->
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">Nome</span>
              </div>
              {% render_field form.nome class+="form-control" %}
            </div>

            <!-- CNPJ -->
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">CNPJ</span>
              </div>
              {% render_field form.cnpj class+="form-control" %}
            </div>

            <hr>
            <div class="text-right">
              <a href="{% url 'website:lista_empresas' %}" class="btn btn-outline-primary">Voltar</a>
              <button class="btn btn-primary">Enviar</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

website/templates/website/exclui.html
<!-- Estendemos do template base -->
{% extends "website/_layouts/base.html" %}

<!-- Bloco que define o <title></title> da nossa página -->
{% block title %}Página Inicial{% endblock %}

<!-- Bloco de conteúdo da nossa página -->
{% block conteudo %}
  <div class="container mt-5">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Exclusão de Empresa</h5>

        <p class="card-text">
          Você tem certeza que quer excluir a empresa <b>{{ empresa.nome }}</b>?
        </p>

        <form method="post">
          {% csrf_token %}

          <hr />
          <div class="text-right">
            <a href="{% url 'website:lista_empresas' %}" class="btn btn-outline-danger">
              Cancelar
            </a>
            <button class="btn btn-danger">Excluir</button>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

website/templates/website/index.html
<!-- Estendemos do template base -->
{% extends "website/_layouts/base.html" %}

<!-- Bloco que define o <title></title> da nossa página -->
{% block title %}Página Inicial{% endblock %}

<!-- Bloco de conteúdo da página -->
{% block conteudo %}
<!-- Empresa -->
<div class="container mt-5">
  <div class="row">
    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Cadastrar Empresa</h5>
          <p class="card-text">
            Cadastre aqui uma nova <code>Empresa</code>.
          </p>
          <a href="{% url 'website:cadastra_empresa' %}"
             class="btn btn-primary">
            Nova Empresa
          </a>
        </div>
      </div>
    </div>
    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Lista de Empresas</h5>
          <p class="card-text">
            Veja aqui a lista de <code>Empresas</code> cadastradas.
          </p>
          <a href="{% url 'website:lista_empresas' %}"
             class="btn btn-primary">
            Ver Lista
          </a>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- Serviço -->
<div class="container mt-5">
  <div class="row">
    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Cadastrar Serviço</h5>
          <p class="card-text">
            Cadastre aqui um novo <code>Serviço</code>.
          </p>
          <a href="{% url 'website:cadastra_servico' %}"
             class="btn btn-primary">
            Novo Serviço
          </a>
        </div>
      </div>
    </div>
    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Lista de Serviços</h5>
          <p class="card-text">
            Veja aqui a lista de <code>Serviços</code> cadastrados.
          </p>
          <a href="{% url 'website:lista_servicos' %}"
             class="btn btn-primary">
            Ver Lista
          </a>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Vendedor -->
<div class="container mt-5">
  <div class="row">
    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Cadastrar Vendedor</h5>
          <p class="card-text">
            Cadastre aqui um novo <code>Vendedor</code>.
          </p>
          <a href="{% url 'website:cadastra_vendedor' %}"
             class="btn btn-primary">
            Novo Serviço
          </a>
        </div>
      </div>
    </div>
    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Lista de Vendedores</h5>
          <p class="card-text">
            Veja aqui a lista de <code>Vendedores</code> cadastrados.
          </p>
          <a href="{% url 'website:lista_vendedores' %}"
             class="btn btn-primary">
            Ver Lista
          </a>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Venda -->
<div class="container mt-5">
  <div class="row">
    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Registrar Venda</h5>
          <p class="card-text">
            Registre aqui uma nova <code>Venda</code>.
          </p>
          <a href="{% url 'website:cadastra_venda' %}"
             class="btn btn-primary">
            Nova Venda
          </a>
        </div>
      </div>
    </div>
    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Lista de Vendas</h5>
          <p class="card-text">
            Veja aqui a lista de <code>Vendas</code> realizadas.
          </p>
          <a href="{% url 'website:lista_vendas' %}"
             class="btn btn-primary">
            Ver Lista
          </a>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

website/templates/website/lista_servico.html
{% extends "website/_layouts/base.html" %}

{% block title %}Lista de Serviços{% endblock %}

{% load primeira_letra %}

{% block conteudo %}
<div class="container mt-5">
  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Lista de Serviços</h5>

          {% if servicos|length > 0 %}
            <p class="card-text">
              Aqui está a lista de <code>Serviços</code> cadastrados.
            </p>

            <table class="table">
              <thead class="thead-dark">
              <tr>
                <th scope="col"></th>
                <th scope="col">Nome</th>
                <th scope="col">Preço</th>
                <th scope="col">Comissão (%)</th>
                <th scope="col">Prestadora</th>
                <th scope="col" class="text-center">Ações</th>
              </tr>
              </thead>
              <tbody>
              {% for servico in servicos %}
                <tr>
                  <th scope="row">{{ servico.nome_servico|primeira_letra }}</th>
                  <td>{{ servico.nome_servico }}</td>
                  <td>{{ servico.preco }}</td>
                  <td>{{ servico.comissao_servico }}</td>
                  <td>{{ servico.empresa_prestadora }}</td>
                  <td class="text-center">
                    <a href="{% url 'website:atualiza_servico' pk=servico.id %}"
                       class="btn btn-primary">
                      Atualizar
                    </a>
                    <a href="{% url 'website:deleta_servico' pk=servico.id %}"
                      class="btn btn-danger">
                        Excluir
                    </a>
                  </td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
        {% else %}
          <div class="text-center mt-5 mb-5 jumbotron">
            <h5>Nenhum <code>Serviço</code> cadastrado ainda.</h5>
          </div>
        {% endif %}
          <hr />
          <div class="text-right">
            <a href="{% url 'website:cadastra_servico' %}" class="btn btn-primary">
              Cadastrar Serviço
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

website/templates/website/lista_venda.html
{% extends "website/_layouts/base.html" %}

{% block title %}Lista de Vendas{% endblock %}

{% load primeira_letra %}

{% block conteudo %}
<div class="container mt-5">
  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Lista de Vendas</h5>

          {% if vendas|length > 0 %}
            <p class="card-text">
              Aqui está a lista de <code>Vendas</code> registradas.
            </p>

            <table class="table">
              <thead class="thead-dark">
              <tr>
                <th scope="col"></th>
                <th scope="col">Vendedor</th>
                <th scope="col">Serviço</th>
                <th scope="col">Empresa</th>
                <th scope="col" class="text-center">Ações</th>
              </tr>
              </thead>
              <tbody>
              {% for venda in vendas %}
                <tr>
                  <th scope="row">{{ venda.id_vendedor|primeira_letra }}</th>
                  <td>{{ venda.id_vendedor }}</td>
                  <td>{{ venda.id_servico }}</td>
                  <td>{{ venda.id_empresa }}</td>
                  <td class="text-center">
                    <a href="{% url 'website:atualiza_venda' pk=venda.id %}"
                       class="btn btn-primary">
                      Atualizar
                    </a>
                    <a href="{% url 'website:deleta_venda' pk=venda.id %}"
                      class="btn btn-danger">
                        Excluir
                    </a>
                  </td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
        {% else %}
          <div class="text-center mt-5 mb-5 jumbotron">
            <h5>Nenhuma <code>Venda</code> registrada ainda.</h5>
          </div>
        {% endif %}
          <hr />
          <div class="text-right">
            <a href="{% url 'website:cadastra_venda' %}" class="btn btn-primary">
              Registrar Venda
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

website/templates/website/lista_vendedor.html
{% extends "website/_layouts/base.html" %}

{% block title %}Lista de Vendedor{% endblock %}

{% load primeira_letra %}

{% block conteudo %}
<div class="container mt-5">
  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Lista de Vendedores</h5>

          {% if vendedores|length > 0 %}
            <p class="card-text">
              Aqui está a lista de <code>Vendedores</code> cadastrados.
            </p>

            <table class="table">
              <thead class="thead-dark">
              <tr>
                <th scope="col"></th>
                <th scope="col">Nome</th>
                <th scope="col">Comissão</th>
                <th scope="col">Empresa</th>
                <th scope="col" class="text-center">Ações</th>
              </tr>
              </thead>
              <tbody>
              {% for vendedor in vendedores %}
                <tr>
                  <th scope="row">{{ vendedor.nome_vendedor|primeira_letra }}</th>
                  <td>{{ vendedor.nome_vendedor }}</td>
                  <td>{{ vendedor.comissao_vendedor }}</td>
                  <td>{{ vendedor.empresa_vendedor }}</td>
                  <td class="text-center">
                    <a href="{% url 'website:atualiza_vendedor' pk=vendedor.id %}"
                       class="btn btn-primary">
                      Atualizar
                    </a>
                    <a href="{% url 'website:deleta_vendedor' pk=vendedor.id %}"
                      class="btn btn-danger">
                        Excluir
                    </a>
                  </td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
        {% else %}
          <div class="text-center mt-5 mb-5 jumbotron">
            <h5>Nenhum <code>Vendedor</code> cadastrado ainda.</h5>
          </div>
        {% endif %}
          <hr />
          <div class="text-right">
            <a href="{% url 'website:cadastra_vendedor' %}" class="btn btn-primary">
              Cadastrar Vendedor
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}