empresa_xyz/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('', include('website.urls', namespace='website')),

    path('admin/', admin.site.urls),
]

website/urls.py
from website.views import IndexTemplateView, EmpresaListView, EmpresaUpdateView, EmpresaCreateView, \
    EmpresaDeleteView, ServicoListView, ServicoUpdateView, ServicoCreateView, ServicoDeleteView, \
    VendedorListView, VendedorUpdateView, VendedorCreateView, VendedorDeleteView, VendaListView, \
    VendaUpdateView, VendaCreateView, VendaDeleteView

from django.urls import path

app_name = 'website'

urlpatterns = [
    # GET /
    path('', IndexTemplateView.as_view(), name="index"),

    # GET /empresa/cadastrar
    path('empresa/cadastrar', EmpresaCreateView.as_view(), name="cadastra_empresa"),

    # GET /empresas
    path('empresas/', EmpresaListView.as_view(), name="lista_empresas"),

    # GET/POST /empresa/{pk}
    path('empresa/<pk>', EmpresaUpdateView.as_view(), name="atualiza_empresa"),

    # GET/POST /empresas/excluir/{pk}
    path('empresa/excluir/<pk>', EmpresaDeleteView.as_view(), name="deleta_empresa"),

    ##################################################################################

    # GET /servico/cadastrar
    path('servico/cadastrar', ServicoCreateView.as_view(), name="cadastra_servico"),

    # GET /servicos
    path('servicos/', ServicoListView.as_view(), name="lista_servicos"),

    # GET/POST /servico/{pk}
    path('servico/<pk>', ServicoUpdateView.as_view(), name="atualiza_servico"),

    # GET/POST /servicos/excluir/{pk}
    path('servico/excluir/<pk>', ServicoDeleteView.as_view(), name="deleta_servico"),

    ##################################################################################

    # GET /vendedor/cadastrar
    path('vendedor/cadastrar', VendedorCreateView.as_view(), name="cadastra_vendedor"),

    # GET /vendedores
    path('vendedores/', VendedorListView.as_view(), name="lista_vendedores"),

    # GET/POST /vendedor/{pk}
    path('vendedor/<pk>', VendedorUpdateView.as_view(), name="atualiza_vendedor"),

    # GET/POST /vendedores/excluir/{pk}
    path('vendedor/excluir/<pk>', VendedorDeleteView.as_view(), name="deleta_vendedor"),

    # Testando chamada de Vendedores por empresa
    #path('vendedores/', VendedorEmpresa.as_view(), name="vendedor_empresa")

    ##################################################################################

    # GET /venda/cadastrar
    path('venda/cadastrar', VendaCreateView.as_view(), name="cadastra_venda"),

    # GET /vendas
    path('vendas/', VendaListView.as_view(), name="lista_vendas"),

    # GET/POST /venda/{pk}
    path('venda/<pk>', VendaUpdateView.as_view(), name="atualiza_venda"),

    # GET/POST /vendas/excluir/{pk}
    path('venda/excluir/<pk>', VendaDeleteView.as_view(), name="deleta_venda"),

]

website/forms.py
from empresa_xyz.models import Empresa, Servico, Vendedor, Venda
from django import forms


# FORMULÁRIO DE CADASTRO DE EMPRESAS

class InsereEmpresaForm(forms.ModelForm):

    class Meta:
        model = Empresa

        fields = [
            'nome',
            'cnpj',
        ]

# FORMULÁRIO DE CADASTRO DE EMPRESAS

class InsereServicoForm(forms.ModelForm):

    class Meta:
        model = Servico

        fields = [
            'nome_servico',
            'comissao_servico',
            'empresa_prestadora',
            'preco',
        ]

# FORMULÁRIO DE CADASTRO DE VENDEDORES

class InsereVendedorForm(forms.ModelForm):

    class Meta:
        model = Vendedor

        fields = [
            'nome_vendedor',
            'comissao_vendedor',
            'empresa_vendedor',
        ]

# FORMULÁRIO DE VENDAS

class InsereVendaForm(forms.ModelForm):

    class Meta:
        model = Venda

        fields = [
            'id_empresa',
            'id_vendedor',
            'id_servico',
        ]

website/views.py
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, UpdateView, CreateView, DeleteView
from empresa_xyz.models import Empresa, Servico, Vendedor, Venda
from website.forms import InsereEmpresaForm, InsereServicoForm, InsereVendedorForm, InsereVendaForm
from django.shortcuts import render


# PÁGINA PRINCIPAL
class IndexTemplateView(TemplateView):
    template_name = "website/index.html"


# LISTA DE EMPRESAS
class EmpresaListView(ListView):
    template_name = "website/lista.html"
    model = Empresa
    context_object_name = "empresas"


# CADASTRAMENTO DE EMPRESAS
class EmpresaCreateView(CreateView):
    template_name = "website/cria.html"
    model = Empresa
    form_class = InsereEmpresaForm
    success_url = reverse_lazy("website:lista_empresas")


# ATUALIZAÇÃO DE EMPRESAS
class EmpresaUpdateView(UpdateView):
    template_name = "website/atualiza.html"
    model = Empresa
    fields = '__all__'
    context_object_name = 'empresa'
    success_url = reverse_lazy("website:lista_empresas")


# EXCLUSÃO DE EMPRESAS
class EmpresaDeleteView(DeleteView):
    template_name = "website/exclui.html"
    model = Empresa
    context_object_name = 'empresa'
    success_url = reverse_lazy("website:lista_empresas")

########################################################

# LISTA DE SERVICOS
class ServicoListView(ListView):
    template_name = "website/lista_servico.html"
    model = Servico
    context_object_name = "servicos"


# CADASTRAMENTO DE SERVICOS
class ServicoCreateView(CreateView):
    template_name = "website/cria_servico.html"
    model = Servico
    form_class = InsereServicoForm
    success_url = reverse_lazy("website:lista_servicos")


# ATUALIZAÇÃO DE SERVICOS
class ServicoUpdateView(UpdateView):
    template_name = "website/atualiza_servico.html"
    model = Servico
    fields = '__all__'
    context_object_name = 'servico'
    success_url = reverse_lazy("website:lista_servicos")


# EXCLUSÃO DE SERVICOS
class ServicoDeleteView(DeleteView):
    template_name = "website/exclui_servico.html"
    model = Servico
    context_object_name = 'servico'
    success_url = reverse_lazy("website:lista_servicos")

###########################################################

# LISTA DE VENDEDORES
class VendedorListView(ListView):
    template_name = "website/lista_vendedor.html"
    model = Vendedor
    context_object_name = "vendedores"


# CADASTRAMENTO DE VENDEDORES
class VendedorCreateView(CreateView):
    template_name = "website/cria_vendedor.html"
    model = Vendedor
    form_class = InsereVendedorForm
    success_url = reverse_lazy("website:lista_vendedores")


# ATUALIZAÇÃO DE VENDEDORES
class VendedorUpdateView(UpdateView):
    template_name = "website/atualiza_vendedor.html"
    model = Vendedor
    fields = '__all__'
    context_object_name = 'vendedor'
    success_url = reverse_lazy("website:lista_vendedores")


# EXCLUSÃO DE VENDEDORES
class VendedorDeleteView(DeleteView):
    template_name = "website/exclui_vendedor.html"
    model = Vendedor
    context_object_name = 'vendedor'
    success_url = reverse_lazy("website:lista_vendedores")


###########################################################

# VENDAS REALIZADAS
class VendaListView(ListView):
    template_name = "website/lista_venda.html"
    model = Venda
    context_object_name = "vendas"

# CADASTRAMENTO DE VENDAS
class VendaCreateView(CreateView):
    template_name = "website/cria_venda.html"
    model = Venda
    form_class = InsereVendaForm
    success_url = reverse_lazy("website:lista_vendas")

# ATUALIZAÇÃO DE VENDAS
class VendaUpdateView(UpdateView):
    template_name = "website/atualiza_venda.html"
    model = Venda
    fields = '__all__'
    context_object_name = 'venda'
    success_url = reverse_lazy("website:lista_vendas")

# EXCLUSÃO DE VENDAS
class VendaDeleteView(DeleteView):
    template_name = "website/exclui_venda.html"
    model = Venda
    context_object_name = 'venda'
    success_url = reverse_lazy("website:lista_vendas")

###########################################################

'''def VendedorEmpresa(request):
    vendedores = Vendedor.objetos.all()

    contexto = {
        'vendedores': vendedores
    }

    return render(
        request,
        "templates/vendedor_empresa.html",
        contexto
    )'''

'''class VendedorEmpresa(UpdateView):
    template_name = "website/vendedor_empresa.html"
    model = Vendedor
    fields = '__all__'
    context_object_name = "vendedores"

    def get_object(self, queryset=None, nome_empresa):
        vendedor = None
        id = self.kwargs.get(self.pk_url_kwarg)

        if id is not None:
            vendedor = Vendedor.objetos.filter(id=id).filter(empresa_vendedor=nome_empresa).all()

        return vendedor'''

website/templates/website/_layouts/base.html
<!DOCTYPE html>
<html>
    {% load static tempo_atual %}

    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">

        <!-- Title -->
        <title>{% block title %}Sistema de Gerenciamento XYZ{% endblock %}</title>

        <!-- EBI -->
        <link rel="shortcut icon" href="{% static 'website/img/ebi.png' %}" type="image/png">

        <!-- Arquivos CSS -->
        <link rel="stylesheet" type="text/css" href="{% static 'website/css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'website/css/master.css' %}">

        {% block styles %}{% endblock %}
    </head>

    <body>
        <!-- Navbar -->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{% url 'website:index' %}">
              <img src="{% static 'website/img/ebi.png' %}" height="45px">
            </a>
            <button class="navbar-toggler" type="button" 
                data-toggle="collapse" data-target="#navbarSupportedContent" 
                aria-controls="navbarSupportedContent" aria-expanded="false" 
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'website:index' %}">Página Inicial</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'website:lista_empresas' %}">Empresas</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'website:lista_servicos' %}">Servicos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'website:lista_vendedores' %}">Vendedores</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'website:lista_vendas' %}">Vendas</a>
                    </li>
                </ul>
                <ul class="navbar-nav float-right">
                    <li class="nav-item">
                        <a class="nav-link" href="#"><b>Hora: </b>{% tempo_atual %}</a>
                    </li>
                </ul>
            </div>
        </nav>
        
        <!-- Conteúdo do site -->
        {% block conteudo %}{% endblock %}

        <!-- Scripts .js -->
        <script src="{% static 'website/js/jquery.min.js' %}"></script>
        <script src="{% static 'website/js/bootstrap.min.js' %}"></script>

        {% block scripts %}{% endblock %}

        <script src="{% static 'website/js/scripts.js' %}"></script>
    </body>
</html>